HIRING_CANDIDATES_TRACKER_TEMPLATE_URL=https://foo.com/ctt
HIRING_INTERVIEW_TEMPLATES_FOLDER="https://drive.google.com/blah/blah"
HIRING_DEFAULT_INTERVIEW_TEMPLATE="https://drive.google.com/bar/baz"
STAFF_DEFAULT_OPENINGS_POSTED_AT="Indeed, Monster.com"
STAFF_HIRING_RECORDS_FOLDER_URL="https://drive.google.com/foo/foo"

ATLASSIAN_ADMIN_PORTAL_URL="https://admin.atlassian.com/s/blahblahblah/users"


HAS_SENSITIVE_DATA=1
TRACKS_STAFF=1
GEN_SEC_LVL=3
HR_COMPLIANCE_AGENCY=Gusto
ORG_CHART='https://foo.com'

INTERNAL_SUPPORT_NUMBER=555-555-5555
INTERNAL_SUPPORT_EMAIL=help@acme.com

MANAGES_NETWORK=0
MANAGES_PHYSICAL_NETWORK=0
MANAGES_CLOUD_NETWORK=0

MANAGES_DEVICES=0

# for policy-security
COMPANY_EMAIL_DOMAIN='foo.com'
HAS_CARDHOLDER_DATA=1
HAS_CENTRAL_ENDPOINT_PROTECTION=1
ANTI_VIRUS_CLIENT='Sophos Home client'
CENTRAL_ENDPOINT_PROTECTION='Sophos Home client'
MASTER_STAFF_LOG='https://foo.com/master-staff-log'
TRACKS_APPROVED_TECHNOLOGIES=1
PRODUCTION_AND_SENSITIVE_TECHNOLOGIES='https://foo.com/approved-tech-inventory'
COMPONENT_UPDATE_CYCLE='monthly'
PASSWORD_MANAGER='KeePassXC'
PASSWORD_MANAGER_MACOS_INSTALL_URL='http://foo.com'
PASSWORD_MANAGER_EXTENSION_URL='https://foo.com/ext'
PASSWORD_MANAGER_WINDOWS_10_INSTALL_URL='http://foo.com/win'

SHARED_DRIVE_SECURITY_AND_COMPLIANCE='https://drive.google.com/foo'
